<a href="https://colab.research.google.com/github/samuelsushanth/machinelearninganddataanalysisprojects/blob/main/BivariateAnalysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# import necessary libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sb
import plotly.express as px

import warnings
warnings.filterwarnings('ignore')

In [2]:
# read the dataset
df=pd.read_csv('EDA_Gold_Silver_prices.csv')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 241 entries, 0 to 240
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Month        241 non-null    object
 1   SilverPrice  241 non-null    float64
 2   GoldPrice    241 non-null    float64
dtypes: float64(2), object(1)
memory usage: 5.8+ KB

In [4]:
df.describe()

       SilverPrice     GoldPrice
count   241.000000    241.000000
mean    685.282282  41180.102697
std     498.538816  28935.099175
min     155.800000  11084.770000
25%     226.610000  14388.340000
50%     537.930000  28636.080000
75%    1070.970000  74476.640000
max    1895.060000  95194.240000

In [5]:
df.head(10)

    Month  SilverPrice  GoldPrice
0  Mar-97       186.48   12619.24
1  Apr-97       170.65   12338.59
2  May-97       170.44   12314.94
3  Jun-97       169.96   12202.78
4  Jul-97       155.80   11582.07
5  Aug-97       162.16   11640.38
6  Sep-97       172.13   11755.57
7  Oct-97       181.57   11769.89
8  Nov-97       187.99   11370.19
9  Dec-97       224.16   11324.79

In [6]:
print(df.columns)

Index(['Month', 'SilverPrice', 'GoldPrice'], dtype='object')

In [8]:
# Display all rows and columns without truncation
pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)
pd.set_option("display.expand_frame_repr", False)

# Print the full DataFrame
print(df)

      Month  SilverPrice  GoldPrice
0    Mar-97       186.48   12619.24
1    Apr-97       170.65   12338.59
2    May-97       170.44   12314.94
3    Jun-97       169.96   12202.78
4    Jul-97       155.80   11582.07
5    Aug-97       162.16   11640.38
6    Sep-97       172.13   11755.57
7    Oct-97       181.57   11769.89
8    Nov-97       187.99   11370.19
9    Dec-97       224.16   11324.79
10   Jan-98       230.08   11378.25
11   Feb-98       261.75   11576.23
12   Mar-98       243.81   11690.84
13   Apr-98       249.37   12225.02
14   May-98       225.54   12075.24
15   Jun-98       222.24   12349.86
16   Jul-98       232.46   12450.03
17   Aug-98       220.73   12142.73
18   Sep-98       213.74   12287.69
19   Oct-98       211.80   12531.16
20   Nov-98       211.21   12463.97
21   Dec-98       207.96   12412.18
22   Jan-99       219.44   12203.20
23   Feb-99       235.52   12203.06
24   Mar-99       220.61   12135.19
25   Apr-99       217.57   12075.25
26   May-99       226.61   11823.60
27   Jun-99       219.02   11272.20
28   Jul-99       226.31   11084.77
29   Aug-99       230.06   11155.98
30   Sep-99       229.82   11526.30
31   Oct-99       235.38   13502.09
32   Nov-99       225.32   12723.39
33   Dec-99       226.61   12309.24
34   Jan-00       227.98   12382.68
35   Feb-00       231.00   13077.75
36   Mar-00       222.37   12483.33
37   Apr-00       222.72   12205.39
38   May-00       221.88   12100.23
39   Jun-00       225.78   12769.55
40   Jul-00       224.71   12609.06
41   Aug-00       225.15   12541.03
42   Sep-00       226.92   12558.90
43   Oct-00       226.27   12515.53
44   Nov-00       220.78   12444.55
45   Dec-00       218.04   12690.44
46   Jan-01       218.83   12355.90
47   Feb-01       212.75   12181.90
48   Mar-01       205.10   12262.59
49   Apr-01       205.51   12186.79
50   May-01       208.12   12778.39
51   Jun-01       205.32   12702.23
52   Jul-01       200.56   12611.85
53   Aug-01       198.27   12836.74
54   Sep-01       209.25   13503.83
55   Oct-01       212.19   13592.68
56   Nov-01       197.92   13254.95
57   Dec-01       209.23   13217.92
58   Jan-02       217.59   13606.99
59   Feb-02       216.57   14388.34
60   Mar-02       222.74   14332.32
61   Apr-02       225.27   14806.95
62   May-02       232.04   15410.01
63   Jun-02       240.95   15725.33
64   Jul-02       241.17   15277.25
65   Aug-02       221.65   15075.69
66   Sep-02       222.55   15459.50
67   Oct-02       213.93   15311.83
68   Nov-02       219.02   15396.81
69   Dec-02       224.21   15977.80
70   Jan-03       232.76   17104.25
71   Feb-03       223.45   17135.72
72   Mar-03       216.64   16224.16
73   Apr-03       214.92   15548.35
74   May-03       223.78   16746.68
75   Jun-03       212.87   16649.12
76   Jul-03       224.92   16229.25
77   Aug-03       231.01   16526.12
78   Sep-03       238.71   17374.81
79   Oct-03       228.73   17199.35
80   Nov-03       236.99   17748.70
81   Dec-03       257.74   18553.38
82   Jan-04       289.57   18806.25
83   Feb-04       293.23   18329.50
84   Mar-04       328.37   18306.02
85   Apr-04       311.30   17716.56
86   May-04       266.05   17362.97
87   Jun-04       267.81   17859.21
88   Jul-04       293.55   18329.56
89   Aug-04       311.06   18560.59
90   Sep-04       295.92   18682.41
91   Oct-04       327.21   19250.39
92   Nov-04       338.98   19821.18
93   Dec-04       313.33   19442.83
94   Jan-05       291.23   18554.21
95   Feb-05       308.92   18490.66
96   Mar-05       317.53   18954.91
97   Apr-05       313.07   18775.16
98   May-05       306.74   18347.86
99   Jun-05       319.76   18770.58
100  Jul-05       306.68   18480.70
101  Aug-05       306.57   19105.09
102  Sep-05       315.91   20028.03
103  Oct-05       345.09   21062.00
104  Nov-05       359.58   21796.08
105  Dec-05       396.65   23290.06
106  Jan-06       407.79   24413.14
107  Feb-06       422.09   24603.51
108  Mar-06       461.44   24776.99
109  Apr-06       567.78   27448.49
110  May-06       607.50   30668.98
111  Jun-06       496.21   27455.73
112  Jul-06       520.88   29439.75
113  Aug-06       570.29   29440.30
114  Sep-06       534.97   27588.91
115  Oct-06       528.14   26634.49
116  Nov-06       582.45   28162.44
117  Dec-06       593.56   28110.41
118  Jan-07       570.48   27985.57
119  Feb-07       615.88   29356.70
120  Mar-07       579.50   28832.08
121  Apr-07       578.83   28636.08
122  May-07       537.93   27220.91
123  Jun-07       536.20   26726.01
124  Jul-07       522.76   26892.24
125  Aug-07       503.37   27160.49
126  Sep-07       521.56   28748.42
127  Oct-07       542.19   29816.80
128  Nov-07       578.66   31798.42
129  Dec-07       564.48   31678.33
130  Jan-08       632.29   35025.78
131  Feb-08       701.87   36642.46
132  Mar-08       775.49   39082.77
133  Apr-08       700.96   36416.00
134  May-08       718.20   37435.38
135  Jun-08       729.63   38087.88
136  Jul-08       773.80   40256.56
137  Aug-08       625.97   36026.85
138  Sep-08       555.58   37815.02
139  Oct-08       507.20   39235.79
140  Nov-08       483.55   37284.82
141  Dec-08       501.82   39696.27
142  Jan-09       556.73   41938.42
143  Feb-09       661.39   46416.55
144  Mar-09       672.41   47387.48
145  Apr-09       626.90   44573.36
146  May-09       684.92   45070.86
147  Jun-09       700.33   45178.09
148  Jul-09       649.34   45317.28
149  Aug-09       697.27   45872.80
150  Sep-09       798.50   48273.82
151  Oct-09       806.59   48737.49
152  Nov-09       832.51   52484.94
153  Dec-09       822.77   52912.18
154  Jan-10       815.23   51344.51
155  Feb-10       735.29   50745.87
156  Mar-10       780.50   50654.61
157  Apr-10       808.47   51115.41
158  May-10       843.70   55173.35
159  Jun-10       859.34   57410.36
160  Jul-10       841.85   55916.83
161  Aug-10       856.25   56616.02
162  Sep-10       946.05   58511.77
163  Oct-10      1039.07   59609.35
164  Nov-10      1191.08   61476.45
165  Dec-10      1324.57   62809.82
166  Jan-11      1293.84   61743.40
167  Feb-11      1399.04   62486.08
168  Mar-11      1611.23   64031.82
169  Apr-11      1895.06   65730.36
170  May-11      1676.20   67907.28
171  Jun-11      1605.47   68594.58
172  Jul-11      1684.10   69854.13
173  Aug-11      1826.14   79645.34
174  Sep-11      1821.03   84580.51
175  Oct-11      1574.44   82055.02
176  Nov-11      1676.94   88150.88
177  Dec-11      1595.18   86328.88
178  Jan-12      1570.17   84732.63
179  Feb-12      1678.47   85781.78
180  Mar-12      1658.30   84338.83
181  Apr-12      1633.13   85434.05
182  May-12      1560.54   86343.66
183  Jun-12      1567.92   89578.52
184  Jul-12      1523.19   88525.34
185  Aug-12      1600.13   90579.25
186  Sep-12      1833.63   95194.24
187  Oct-12      1757.55   92496.06
188  Nov-12      1793.35   94207.98
189  Dec-12      1740.87   92015.41
190  Jan-13      1687.06   90803.41
191  Feb-13      1629.97   87471.13
192  Mar-13      1565.88   86644.52
193  Apr-13      1378.70   80903.29
194  May-13      1267.87   77818.64
195  Jun-13      1231.26   78355.69
196  Jul-13      1178.27   76847.39
197  Aug-13      1383.89   85442.04
198  Sep-13      1437.07   85891.21
199  Oct-13      1350.77   81142.34
200  Nov-13      1301.68   80007.36
201  Dec-13      1218.52   75670.26
202  Jan-14      1234.87   77312.91
203  Feb-14      1298.32   80943.59
204  Mar-14      1262.99   81456.73
205  Apr-14      1191.20   78370.05
206  May-14      1147.81   76477.43
207  Jun-14      1187.80   76378.35
208  Jul-14      1256.71   78718.95
209  Aug-14      1201.83   78867.16
210  Sep-14      1118.37   75285.57
211  Oct-14      1052.92   74997.34
212  Nov-14       984.74   72491.16
213  Dec-14      1021.88   75291.99
214  Jan-15      1070.97   77715.80
215  Feb-15      1041.26   76113.23
216  Mar-15      1014.19   73605.25
217  Apr-15      1025.45   75236.65
218  May-15      1074.12   76484.80
219  Jun-15      1026.56   75451.46
220  Jul-15       958.06   71812.23
221  Aug-15       972.25   72746.31
222  Sep-15       976.67   74476.64
223  Oct-15      1029.04   75438.75
224  Nov-15       954.56   71759.82
225  Dec-15       938.00   71140.66
226  Jan-16       949.24   73882.06
227  Feb-16      1035.04   81857.57
228  Mar-16      1037.05   83496.73
229  Apr-16      1087.44   82572.44
230  May-16      1133.52   84340.04
231  Jun-16      1163.03   85878.28
232  Jul-16      1343.80   89845.32
233  Aug-16      1311.11   89707.71
234  Sep-16      1291.92   88540.40
235  Oct-16      1178.00   84533.34
236  Nov-16      1175.45   83622.54
237  Dec-16      1115.72   78583.48
238  Jan-17      1151.15   81191.05
239  Feb-17      1203.35   82818.17
240  Mar-17      1162.15   81169.45

In [13]:
# prompt: Bivariate Analysis
# What is the correlation in Gold and Silver prices (round off the answer to two decimal places)? Also, enter a fraction, not a percentage (e.g. 0.34, not 34.00%).

# Calculate the correlation between Gold and Silver prices
correlation = df['GoldPrice'].corr(df['SilverPrice'])

# Round off the correlation to two decimal places
rounded_correlation = round(correlation, 2)

# Print the rounded correlation
rounded_correlation

0.95

In [18]:
# prompt: What is the correlation in Gold and Silver prices for the years 2008(nearest two decimal places )? 125  Aug-07       503.37   27160.49
# 126  Sep-07       521.56   28748.42
# 127  Oct-07       542.19   29816.80
# 128  Nov-07       578.66   31798.42
# 129  Dec-07       564.48   31678.33
# 130  Jan-08       632.29   35025.78
# 131  Feb-08       701.87   36642.46
# 132  Mar-08       775.49   39082.77
# 133  Apr-08

# Filter data for the year 2008
df_2008 = df[df['Month'].str.contains('08')]

print(df_2008)

# Calculate the correlation between Gold and Silver prices for 2008
correlation_2008 = df_2008['GoldPrice'].corr(df_2008['SilverPrice'])

# Round off the correlation to two decimal places
rounded_correlation_2008 = round(correlation_2008, 2)

# Print the rounded correlation for 2008
rounded_correlation_2008

      Month  SilverPrice  GoldPrice
130  Jan-08       632.29   35025.78
131  Feb-08       701.87   36642.46
132  Mar-08       775.49   39082.77
133  Apr-08       700.96   36416.00
134  May-08       718.20   37435.38
135  Jun-08       729.63   38087.88
136  Jul-08       773.80   40256.56
137  Aug-08       625.97   36026.85
138  Sep-08       555.58   37815.02
139  Oct-08       507.20   39235.79
140  Nov-08       483.55   37284.82
141  Dec-08       501.82   39696.27

0.01