<a href="https://colab.research.google.com/github/samuelsushanth/machinelearninganddataanalysisprojects/blob/main/currencies.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# import necessary libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sb
import plotly.express as px

import warnings
warnings.filterwarnings('ignore')

In [2]:
# read the dataset
df=pd.read_csv('currencies.csv')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 52 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Currency                    11 non-null     object
 1   Chinese Yuan                11 non-null     float64
 2   Euro                        11 non-null     float64
 3   Japanese Yen                10 non-null     float64
 4   U.K. Pound Sterling         11 non-null     float64
 5   U.S. Dollar                 11 non-null     float64
 6   Algerian Dinar              9 non-null      float64
 7   Australian Dollar           11 non-null     float64
 8   Bahrain Dinar               11 non-null     float64
 9   Botswana Pula               9 non-null      float64
 10  Brazilian Real              11 non-null     float64
 11  Brunei Dollar               10 non-null     float64
 12  Canadian Dollar             10 non-null     float64
 13  Chilean Peso                11 non-null     float64
 14  Colombian Peso              11 non-null     object
 15  Czech Koruna                8 non-null      float64
 16  Danish Krone                11 non-null     float64
 17  Hungarian Forint            11 non-null     float64
 18  Icelandic Krona             11 non-null     float64
 19  Indian Rupee                9 non-null      float64
 20  Indonesian Rupiah           7 non-null      object
 21  Iranian Rial                6 non-null      object
 22  Israeli New Sheqel          11 non-null     float64
 23  Kazakhstani Tenge           8 non-null      float64
 24  Korean Won                  11 non-null     object
 25  Kuwaiti Dinar               6 non-null      float64
 26  Libyan Dinar                11 non-null     float64
 27  Malaysian Ringgit           8 non-null      float64
 28  Mauritian Rupee             9 non-null      float64
 29  Mexican Peso                11 non-null     float64
 30  Nepalese Rupee              11 non-null     float64
 31  New Zealand Dollar          11 non-null     float64
 32  Norwegian Krone             11 non-null     float64
 33  Rial Omani                  11 non-null     float64
 34  Pakistani Rupee             5 non-null      float64
 35  Nuevo Sol                   7 non-null      float64
 36  Philippine Peso             10 non-null     float64
 37  Polish Zloty                11 non-null     float64
 38  Qatar Riyal                 11 non-null     float64
 39  Russian Ruble               10 non-null     float64
 40  Saudi Arabian Riyal         11 non-null     float64
 41  Singapore Dollar            10 non-null     float64
 42  South African Rand          11 non-null     float64
 43  Sri Lanka Rupee             10 non-null     float64
 44  Swedish Krona               10 non-null     float64
 45  Swiss Franc                 11 non-null     float64
 46  Thai Baht                   9 non-null      float64
 47  Trinidad And Tobago Dollar  10 non-null     float64
 48  Tunisian Dinar              5 non-null      float64
 49  U.A.E. Dirham               11 non-null     float64
 50  Peso Uruguayo               6 non-null      float64
 51  Bolivar Fuerte              11 non-null     float64
dtypes: float64(47), object(5)
memory usage: 4.6+ KB

In [4]:
df.describe()

,Chinese Yuan,Euro,Japanese Yen,U.K. Pound Sterling,U.S. Dollar,Algerian Dinar,Australian Dollar,Bahrain Dinar,Botswana Pula,Brazilian Real,...,South African Rand,Sri Lanka Rupee,Swedish Krona,Swiss Franc,Thai Baht,Trinidad And Tobago Dollar,Tunisian Dinar,U.A.E. Dirham,Peso Uruguayo,Bolivar Fuerte
count,11.000000,11.000000,10.000000,11.000000,11.000000,9.000000,11.000000,11.000000,9.000000,11.000000,...,11.000000,10.000000,10.000000,11.000000,9.000000,10.000000,5.000000,11.000000,6.000000,11.000000
mean,9.308559,1.255129,142.872200,1.058719,1.392623,153.894778,1.845607,0.523626,15.056744,4.565969,...,20.215909,202.273600,11.869910,1.363889,48.951333,9.278535,3.069420,5.114408,42.393300,13.891409
std,0.008280,0.003391,2.451108,0.011189,0.002393,0.159560,0.017809,0.000900,0.124190,0.050809,...,0.336959,0.365212,0.060456,0.003784,0.116725,0.022396,0.006663,0.008796,0.329833,0.023886
min,9.294030,1.246950,139.962000,1.042420,1.388830,153.648000,1.827410,0.522201,14.911200,4.479930,...,19.851900,201.728000,11.762700,1.356890,48.760700,9.237450,3.060350,5.100480,42.026700,13.853600
25%,9.303930,1.253445,140.565000,1.050030,1.391575,153.763000,1.829460,0.523232,14.951000,4.535320,...,19.925550,202.099250,11.828675,1.361530,48.887300,9.265050,3.068220,5.110565,42.174800,13.880950
50%,9.313150,1.256520,143.042000,1.057620,1.392570,153.869000,1.838360,0.523607,15.006700,4.575720,...,20.077300,202.225000,11.870950,1.364510,48.995800,9.284710,3.068840,5.114230,42.311800,13.890900
75%,9.314325,1.257530,144.582500,1.069805,1.393540,154.062000,1.858995,0.523972,15.143000,4.589560,...,20.517550,202.438000,11.922350,1.366440,49.040800,9.289080,3.070680,5.117770,42.586275,13.900600
max,9.316970,1.258340,147.268000,1.073000,1.396840,154.094000,1.873130,0.525213,15.239200,4.648680,...,20.723200,202.886000,11.943900,1.370630,49.069200,9.314370,3.079010,5.129920,42.902600,13.933500

In [5]:
df.head(10)

,Currency,Chinese Yuan,Euro,Japanese Yen,U.K. Pound Sterling,U.S. Dollar,Algerian Dinar,Australian Dollar,Bahrain Dinar,Botswana Pula,...,South African Rand,Sri Lanka Rupee,Swedish Krona,Swiss Franc,Thai Baht,Trinidad And Tobago Dollar,Tunisian Dinar,U.A.E. Dirham,Peso Uruguayo,Bolivar Fuerte
0,"July 01, 2016",9.29446,1.25367,143.645,1.05054,1.39596,NaN,1.87126,0.524882,NaN,...,20.3528,202.763,11.8246,1.36009,NaN,9.28428,3.06035,5.12668,NaN,13.9247
1,"July 05, 2016",9.31515,1.25322,142.715,1.06143,1.39684,154.063,1.85825,0.525213,15.2162,...,20.6240,202.886,11.7627,1.35689,49.0655,9.26724,NaN,5.12992,42.9026,13.9335
2,"July 06, 2016",9.31697,1.25834,140.540,1.07300,1.39286,154.094,1.87313,0.523717,15.2392,...,20.7232,NaN,11.8805,1.36208,49.0692,9.25643,NaN,5.11527,42.6425,13.8938
3,"July 07, 2016",9.31315,1.25737,140.640,1.06911,1.39316,153.957,1.85236,0.523829,15.1430,...,20.4288,202.351,11.9192,1.36098,49.0295,NaN,NaN,5.11637,42.4176,13.8968
4,"July 08, 2016",9.31350,1.25797,140.510,1.07261,1.39257,154.062,1.85974,0.523607,15.1202,...,20.6063,202.271,11.9327,1.36472,49.0408,9.26432,NaN,5.11423,42.2060,13.8909
5,"July 11, 2016",9.29403,1.25769,139.962,1.07050,1.38962,153.742,1.83836,0.522496,15.0067,...,20.0773,201.842,11.9439,1.36641,48.7950,9.23745,3.07068,5.10337,NaN,13.8614
6,"July 12, 2016",9.31021,1.25490,143.369,1.05762,1.39194,153.869,1.83439,0.523368,14.9510,...,19.9238,202.179,11.8614,1.36674,48.9182,9.28617,3.07901,5.11187,NaN,13.8845
7,"July 13, 2016",9.31350,1.25716,145.178,1.04680,1.39193,153.855,1.83101,0.523366,14.9509,...,19.9273,202.175,11.9234,1.37063,48.9958,9.29005,3.06884,5.11187,42.1644,13.8845
8,"July 14, 2016",9.30432,1.24695,144.895,1.05236,1.39122,153.763,1.82791,0.523097,14.9112,...,19.8519,202.074,11.8098,1.36326,48.8873,9.29990,NaN,5.10926,NaN,13.8774
9,"July 15, 2016",9.31532,1.25263,147.268,1.04242,1.39392,NaN,1.82786,0.524115,14.9723,...,20.0040,202.467,11.8409,1.36451,48.7607,9.31437,NaN,5.11917,42.0267,13.9044

In [6]:
print(df.columns)

Index(['Currency', 'Chinese Yuan', 'Euro', 'Japanese Yen',
       'U.K. Pound Sterling', 'U.S. Dollar', 'Algerian Dinar',
       'Australian Dollar', 'Bahrain Dinar', 'Botswana Pula', 'Brazilian Real',
       'Brunei Dollar', 'Canadian Dollar', 'Chilean Peso', 'Colombian Peso',
       'Czech Koruna', 'Danish Krone', 'Hungarian Forint', 'Icelandic Krona',
       'Indian Rupee', 'Indonesian Rupiah', 'Iranian Rial',
       'Israeli New Sheqel', 'Kazakhstani Tenge', 'Korean Won',
       'Kuwaiti Dinar', 'Libyan Dinar', 'Malaysian Ringgit', 'Mauritian Rupee',
       'Mexican Peso', 'Nepalese Rupee', 'New Zealand Dollar',
       'Norwegian Krone', 'Rial Omani', 'Pakistani Rupee', 'Nuevo Sol',
       'Philippine Peso', 'Polish Zloty', 'Qatar Riyal', 'Russian Ruble',
       'Saudi Arabian Riyal', 'Singapore Dollar', 'South African Rand',
       'Sri Lanka Rupee', 'Swedish Krona', 'Swiss Franc', 'Thai Baht',
       'Trinidad And Tobago Dollar', 'Tunisian Dinar', 'U.A.E. Dirham',
       'Peso Uruguayo', 'Bolivar Fuerte'],
      dtype='object')

In [7]:
# Display all rows and columns without truncation
pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)
pd.set_option("display.expand_frame_repr", False)

# Print the full DataFrame
print(df)

         Currency  Chinese Yuan     Euro  Japanese Yen  U.K. Pound Sterling  U.S. Dollar  Algerian Dinar  Australian Dollar  Bahrain Dinar  Botswana Pula  Brazilian Real  Brunei Dollar  Canadian Dollar  Chilean Peso Colombian Peso  Czech Koruna  Danish Krone  Hungarian Forint  Icelandic Krona  Indian Rupee Indonesian Rupiah Iranian Rial  Israeli New Sheqel  Kazakhstani Tenge Korean Won  Kuwaiti Dinar  Libyan Dinar  Malaysian Ringgit  Mauritian Rupee  Mexican Peso  Nepalese Rupee  New Zealand Dollar  Norwegian Krone  Rial Omani  Pakistani Rupee  Nuevo Sol  Philippine Peso  Polish Zloty  Qatar Riyal  Russian Ruble  Saudi Arabian Riyal  Singapore Dollar  South African Rand  Sri Lanka Rupee  Swedish Krona  Swiss Franc  Thai Baht  Trinidad And Tobago Dollar  Tunisian Dinar  U.A.E. Dirham  Peso Uruguayo  Bolivar Fuerte
0   July 01, 2016       9.29446  1.25367       143.645              1.05054      1.39596             NaN            1.87126       0.524882            NaN         4.47993        1.87785              NaN       923.250       4,074.83       33.9707       9.32470           397.682          171.326       94.1451         18,387.60          NaN             5.36607            471.892   1,608.98       0.421232        1.9324            5.57407          49.5771       25.5586         150.820             1.95842          11.6560    0.536748              NaN        NaN          65.6198       5.52074      5.08130        89.3647              5.23486           1.87785             20.3528          202.763        11.8246      1.36009        NaN                     9.28428         3.06035        5.12668            NaN         13.9247
1   July 05, 2016       9.31515  1.25322       142.715              1.06143      1.39684         154.063            1.85825       0.525213        15.2162         4.53611        1.88197          1.80877       920.887       4,070.93           NaN       9.32392           397.738          171.043       94.1513               NaN    43,008.70             5.40438            470.834   1,603.72            NaN        1.9324            5.58806          49.5845       26.1958         150.244             1.93952          11.6797    0.537086              NaN    4.59002          65.4185       5.58220      5.08450        89.7714              5.23815           1.88197             20.6240          202.886        11.7627      1.35689    49.0655                     9.26724             NaN        5.12992        42.9026         13.9335
2   July 06, 2016       9.31697  1.25834       140.540              1.07300      1.39286         154.094            1.87313       0.523717        15.2392         4.58224            NaN          1.81141       921.082       4,132.44           NaN       9.36347           398.956          171.336           NaN               NaN          NaN             5.42520                NaN   1,605.97            NaN        1.9324                NaN              NaN       26.2082         150.387             1.96371          11.7677    0.535556              NaN    4.56859              NaN       5.60277      5.07002        90.0212              5.22321               NaN             20.7232              NaN        11.8805      1.36208    49.0692                     9.25643             NaN        5.11527        42.6425         13.8938
3   July 07, 2016       9.31315  1.25737       140.640              1.06911      1.39316         153.957            1.85236       0.523829        15.1430         4.63032        1.88105          1.80888       925.772       4,183.94       34.0168       9.35620           397.886          170.997       94.0345               NaN          NaN             5.40269            469.859   1,624.15            NaN        1.9324                NaN          49.5297       26.2760         150.378             1.95093          11.7919    0.535670              NaN    4.57235          65.3394       5.57765      5.07110        89.2323              5.22436           1.88105             20.4288          202.351        11.9192      1.36098    49.0295                         NaN             NaN        5.11637        42.4176         13.8968
4   July 08, 2016       9.31350  1.25797       140.510              1.07261      1.39257         154.062            1.85974       0.523607        15.1202         4.64868        1.87914          1.82051       924.753       4,158.90       34.0079       9.36084           396.005          171.147       93.9408               NaN          NaN             5.40596            471.329   1,610.65            NaN        1.9324            5.62946          49.4496       25.9006         150.175             1.91524          11.8161    0.535444              NaN    4.56346          65.5068       5.57041      5.06896        89.4710              5.22215           1.87914             20.6063          202.271        11.9327      1.36472    49.0408                     9.26432             NaN        5.11423        42.2060         13.8909
5   July 11, 2016       9.29403  1.25769       139.962              1.07050      1.38962         153.742            1.83836       0.522496        15.0067         4.58045        1.87001          1.82415       919.236       4,103.04       33.9872       9.35366           395.416          170.895       93.3027         18,220.70    42,869.70             5.39590                NaN   1,610.85       0.419387        1.9324            5.53833          49.3686       25.6519         149.787             1.90724          11.8300    0.534308          145.722        NaN          65.4442       5.56681      5.05822        89.2172              5.21107           1.87001             20.0773          201.842        11.9439      1.36641    48.7950                     9.23745         3.07068        5.10337            NaN         13.8614
6   July 12, 2016       9.31021  1.25490       143.369              1.05762      1.39194         153.869            1.83439       0.523368        14.9510         4.59688        1.87911          1.81174       915.667       4,078.10           NaN       9.33376           392.457          170.470       93.4641         18,305.30    42,939.80             5.39235                NaN   1,597.66       0.420364        1.9324                NaN          49.4508       25.4732         149.591             1.92071          11.7332    0.535200          145.919        NaN          65.6478       5.54087      5.06665            NaN              5.21975           1.87911             19.9238          202.179        11.8614      1.36674    48.9182                     9.28617         3.07901        5.11187            NaN         13.8845
7   July 13, 2016       9.31350  1.25716       145.178              1.04680      1.39193         153.855            1.83101       0.523366        14.9509         4.55774        1.87604          1.80464       915.642       4,053.18       33.9840       9.35060           394.904          170.135       93.5445         18,227.30    42,962.00             5.38816            470.961   1,599.74            NaN        1.9324            5.54893          49.4606       25.6028         149.535             1.91620          11.7099    0.535197          145.952    4.56275          65.9692       5.54115      5.06663        88.8794              5.21972           1.87604             19.9273          202.175        11.9234      1.37063    48.9958                     9.29005         3.06884        5.11187        42.1644         13.8845
8   July 14, 2016       9.30432  1.24695       144.895              1.05236      1.39122         153.763            1.82791       0.523097        14.9112         4.57572        1.87411          1.79676       915.701       4,085.35       33.7162       9.27455           392.824          169.882       93.0917         18,208.30    42,938.50             5.35897            471.554   1,593.92       0.419592        1.9324            5.50852          49.4274       25.4678         149.445             1.90996          11.6274    0.534922              NaN        NaN          65.7324       5.52050      5.06403        88.4502              5.21708           1.87411             19.8519          202.074        11.8098      1.36326    48.8873                     9.29990             NaN        5.10926            NaN         13.8774
9   July 15, 2016       9.31532  1.25263       147.268              1.04242      1.39392             NaN            1.82786       0.524115        14.9723         4.50306        1.87246          1.80862       907.334       4,074.53       33.8500       9.31645           393.811          168.874           NaN         18,240.90          NaN             5.35822            471.872   1,591.58       0.420407        1.9324            5.51785              NaN       25.7764         149.192             1.94927          11.6723    0.535963          146.154    4.56648          65.6526       5.51965      5.07388        88.0537              5.22720           1.87246             20.0040          202.467        11.8409      1.36451    48.7607                     9.31437             NaN        5.11917        42.0267         13.9044
10  July 18, 2016       9.30354  1.25652           NaN              1.04952      1.38883         153.648            1.82741       0.522201            NaN         4.53453        1.87340          1.80326       903.546       4,060.19       33.9514       9.34684           396.123          169.479       93.1923         18,210.40    42,891.20             5.36090            470.648   1,573.13       0.419775        1.9324            5.52547          49.2611       25.6766         149.036             1.95886          11.7644    0.534005          145.626    4.54843          65.1042       5.53492      5.05536        87.6562              5.20812           1.87340             19.8556          201.728            NaN      1.36647        NaN                     9.28514         3.06822        5.10048            NaN         13.8536

In [22]:
import pandas as pd

# Load your dataset (assuming it's already in df)

# Convert 'Date' column to datetime format
df.rename(columns={'Currency': 'Date'}, inplace=True)  # Rename the first column to "Date" if needed
df['Date'] = pd.to_datetime(df['Date'])

# Convert all other columns to numeric values
df_numeric = df.drop(columns=['Date']).replace(',', '', regex=True).apply(pd.to_numeric, errors='coerce')
print(df_numeric)

# Calculate the correlation matrix
correlation_matrix = df_numeric.corr()
print(correlation_matrix)

# Find the correlation between Indian Rupee and other currencies
indian_rupee_correlation = correlation_matrix['Indian Rupee']
print(indian_rupee_correlation)

# Find the currency with the highest correlation (excluding itself)
most_correlated_currency = indian_rupee_correlation.dropna().drop('Indian Rupee').abs().idxmax()
print(most_correlated_currency)

# Print the most correlated currency
print(f"The Indian Rupee is most correlated with the {most_correlated_currency}")

    Chinese Yuan     Euro  Japanese Yen  U.K. Pound Sterling  U.S. Dollar  Algerian Dinar  Australian Dollar  Bahrain Dinar  Botswana Pula  Brazilian Real  Brunei Dollar  Canadian Dollar  Chilean Peso  Colombian Peso  Czech Koruna  Danish Krone  Hungarian Forint  Icelandic Krona  Indian Rupee  Indonesian Rupiah  Iranian Rial  Israeli New Sheqel  Kazakhstani Tenge  Korean Won  Kuwaiti Dinar  Libyan Dinar  Malaysian Ringgit  Mauritian Rupee  Mexican Peso  Nepalese Rupee  New Zealand Dollar  Norwegian Krone  Rial Omani  Pakistani Rupee  Nuevo Sol  Philippine Peso  Polish Zloty  Qatar Riyal  Russian Ruble  Saudi Arabian Riyal  Singapore Dollar  South African Rand  Sri Lanka Rupee  Swedish Krona  Swiss Franc  Thai Baht  Trinidad And Tobago Dollar  Tunisian Dinar  U.A.E. Dirham  Peso Uruguayo  Bolivar Fuerte
0        9.29446  1.25367       143.645              1.05054      1.39596             NaN            1.87126       0.524882            NaN         4.47993        1.87785              NaN       923.250         4074.83       33.9707       9.32470           397.682          171.326       94.1451            18387.6           NaN             5.36607            471.892     1608.98       0.421232        1.9324            5.57407          49.5771       25.5586         150.820             1.95842          11.6560    0.536748              NaN        NaN          65.6198       5.52074      5.08130        89.3647              5.23486           1.87785             20.3528          202.763        11.8246      1.36009        NaN                     9.28428         3.06035        5.12668            NaN         13.9247
1        9.31515  1.25322       142.715              1.06143      1.39684         154.063            1.85825       0.525213        15.2162         4.53611        1.88197          1.80877       920.887         4070.93           NaN       9.32392           397.738          171.043       94.1513                NaN       43008.7             5.40438            470.834     1603.72            NaN        1.9324            5.58806          49.5845       26.1958         150.244             1.93952          11.6797    0.537086              NaN    4.59002          65.4185       5.58220      5.08450        89.7714              5.23815           1.88197             20.6240          202.886        11.7627      1.35689    49.0655                     9.26724             NaN        5.12992        42.9026         13.9335
2        9.31697  1.25834       140.540              1.07300      1.39286         154.094            1.87313       0.523717        15.2392         4.58224            NaN          1.81141       921.082         4132.44           NaN       9.36347           398.956          171.336           NaN                NaN           NaN             5.42520                NaN     1605.97            NaN        1.9324                NaN              NaN       26.2082         150.387             1.96371          11.7677    0.535556              NaN    4.56859              NaN       5.60277      5.07002        90.0212              5.22321               NaN             20.7232              NaN        11.8805      1.36208    49.0692                     9.25643             NaN        5.11527        42.6425         13.8938
3        9.31315  1.25737       140.640              1.06911      1.39316         153.957            1.85236       0.523829        15.1430         4.63032        1.88105          1.80888       925.772         4183.94       34.0168       9.35620           397.886          170.997       94.0345                NaN           NaN             5.40269            469.859     1624.15            NaN        1.9324                NaN          49.5297       26.2760         150.378             1.95093          11.7919    0.535670              NaN    4.57235          65.3394       5.57765      5.07110        89.2323              5.22436           1.88105             20.4288          202.351        11.9192      1.36098    49.0295                         NaN             NaN        5.11637        42.4176         13.8968
4        9.31350  1.25797       140.510              1.07261      1.39257         154.062            1.85974       0.523607        15.1202         4.64868        1.87914          1.82051       924.753         4158.90       34.0079       9.36084           396.005          171.147       93.9408                NaN           NaN             5.40596            471.329     1610.65            NaN        1.9324            5.62946          49.4496       25.9006         150.175             1.91524          11.8161    0.535444              NaN    4.56346          65.5068       5.57041      5.06896        89.4710              5.22215           1.87914             20.6063          202.271        11.9327      1.36472    49.0408                     9.26432             NaN        5.11423        42.2060         13.8909
5        9.29403  1.25769       139.962              1.07050      1.38962         153.742            1.83836       0.522496        15.0067         4.58045        1.87001          1.82415       919.236         4103.04       33.9872       9.35366           395.416          170.895       93.3027            18220.7       42869.7             5.39590                NaN     1610.85       0.419387        1.9324            5.53833          49.3686       25.6519         149.787             1.90724          11.8300    0.534308          145.722        NaN          65.4442       5.56681      5.05822        89.2172              5.21107           1.87001             20.0773          201.842        11.9439      1.36641    48.7950                     9.23745         3.07068        5.10337            NaN         13.8614
6        9.31021  1.25490       143.369              1.05762      1.39194         153.869            1.83439       0.523368        14.9510         4.59688        1.87911          1.81174       915.667         4078.10           NaN       9.33376           392.457          170.470       93.4641            18305.3       42939.8             5.39235                NaN     1597.66       0.420364        1.9324                NaN          49.4508       25.4732         149.591             1.92071          11.7332    0.535200          145.919        NaN          65.6478       5.54087      5.06665            NaN              5.21975           1.87911             19.9238          202.179        11.8614      1.36674    48.9182                     9.28617         3.07901        5.11187            NaN         13.8845
7        9.31350  1.25716       145.178              1.04680      1.39193         153.855            1.83101       0.523366        14.9509         4.55774        1.87604          1.80464       915.642         4053.18       33.9840       9.35060           394.904          170.135       93.5445            18227.3       42962.0             5.38816            470.961     1599.74            NaN        1.9324            5.54893          49.4606       25.6028         149.535             1.91620          11.7099    0.535197          145.952    4.56275          65.9692       5.54115      5.06663        88.8794              5.21972           1.87604             19.9273          202.175        11.9234      1.37063    48.9958                     9.29005         3.06884        5.11187        42.1644         13.8845
8        9.30432  1.24695       144.895              1.05236      1.39122         153.763            1.82791       0.523097        14.9112         4.57572        1.87411          1.79676       915.701         4085.35       33.7162       9.27455           392.824          169.882       93.0917            18208.3       42938.5             5.35897            471.554     1593.92       0.419592        1.9324            5.50852          49.4274       25.4678         149.445             1.90996          11.6274    0.534922              NaN        NaN          65.7324       5.52050      5.06403        88.4502              5.21708           1.87411             19.8519          202.074        11.8098      1.36326    48.8873                     9.29990             NaN        5.10926            NaN         13.8774
9        9.31532  1.25263       147.268              1.04242      1.39392             NaN            1.82786       0.524115        14.9723         4.50306        1.87246          1.80862       907.334         4074.53       33.8500       9.31645           393.811          168.874           NaN            18240.9           NaN             5.35822            471.872     1591.58       0.420407        1.9324            5.51785              NaN       25.7764         149.192             1.94927          11.6723    0.535963          146.154    4.56648          65.6526       5.51965      5.07388        88.0537              5.22720           1.87246             20.0040          202.467        11.8409      1.36451    48.7607                     9.31437             NaN        5.11917        42.0267         13.9044
10       9.30354  1.25652           NaN              1.04952      1.38883         153.648            1.82741       0.522201            NaN         4.53453        1.87340          1.80326       903.546         4060.19       33.9514       9.34684           396.123          169.479       93.1923            18210.4       42891.2             5.36090            470.648     1573.13       0.419775        1.9324            5.52547          49.2611       25.6766         149.036             1.95886          11.7644    0.534005          145.626    4.54843          65.1042       5.53492      5.05536        87.6562              5.20812           1.87340             19.8556          201.728            NaN      1.36647        NaN                     9.28514         3.06822        5.10048            NaN         13.8536
                            Chinese Yuan      Euro  Japanese Yen  U.K. Pound Sterling  U.S. Dollar  Algerian Dinar  Australian Dollar  Bahrain Dinar  Botswana Pula  Brazilian Real  Brunei Dollar  Canadian Dollar  Chilean Peso  Colombian Peso  Czech Koruna  Danish Krone  Hungarian Forint  Icelandic Krona  Indian Rupee  Indonesian Rupiah  Iranian Rial  Israeli New Sheqel  Kazakhstani Tenge  Korean Won  Kuwaiti Dinar  Libyan Dinar  Malaysian Ringgit  Mauritian Rupee  Mexican Peso  Nepalese Rupee  New Zealand Dollar  Norwegian Krone  Rial Omani  Pakistani Rupee  Nuevo Sol  Philippine Peso  Polish Zloty  Qatar Riyal  Russian Ruble  Saudi Arabian Riyal  Singapore Dollar  South African Rand  Sri Lanka Rupee  Swedish Krona  Swiss Franc  Thai Baht  Trinidad And Tobago Dollar  Tunisian Dinar  U.A.E. Dirham  Peso Uruguayo  Bolivar Fuerte
Chinese Yuan                    1.000000  0.151596      0.117566             0.108695     0.291582        0.815216           0.077983       0.291926       0.467693        0.320508       0.499400        -0.186643      0.028821        0.252673     -0.000742      0.190088          0.092517        -0.094406      0.304050          -0.306462      0.914786            0.442994          -0.349278    0.048069       0.051050           NaN           0.235758         0.273543      0.585242       -0.048039            0.158424         0.011336    0.291726         0.808891   0.690147         0.161906      0.415765     0.291630       0.184050             0.291155          0.499400            0.356889         0.296118      -0.044773    -0.069368   0.585148                    0.215925        0.542852       0.291300       0.421574        0.292168
Euro                            0.151596  1.000000     -0.645719             0.531150    -0.210587        0.259964           0.331588      -0.209926       0.469668        0.383645       0.103766         0.638422      0.242743        0.414023      0.952136      0.997624          0.500416         0.409634      0.243851           0.013726     -0.345322            0.643255          -0.522276    0.322905      -0.029612           NaN           0.462882        -0.183599      0.406158        0.247677            0.169274         0.848789   -0.209931        -0.759606  -0.425412        -0.314072      0.609706    -0.210148       0.348002            -0.210800          0.103766            0.382248        -0.234048       0.756618     0.277528   0.370282                   -0.621466        0.257016      -0.210770      -0.047889       -0.210364
Japanese Yen                    0.117566 -0.645719      1.000000            -0.970308     0.210295       -0.388099          -0.582032       0.209957      -0.627015       -0.641122      -0.260258        -0.662233     -0.809751       -0.725137     -0.629068     -0.668736         -0.572344        -0.834549     -0.270123          -0.076080      0.558619           -0.798265           0.610230   -0.796719       0.376778           NaN          -0.602250         0.167648     -0.497609       -0.602069            0.008359        -0.818583    0.209915         0.977676  -0.149566         0.717931     -0.806694     0.210217      -0.774645             0.209975         -0.260258           -0.629790         0.216936      -0.484786     0.209928  -0.458043                    0.952893       -0.147436       0.210296      -0.513065        0.210351
U.K. Pound Sterling             0.108695  0.531150     -0.970308             1.000000    -0.042303        0.613186           0.579213      -0.042220       0.689069        0.731765       0.325791         0.670759      0.702740        0.792206      0.491249      0.564435          0.486629         0.760730      0.314681          -0.051199     -0.237550            0.846940          -0.497732    0.661773      -0.492609           NaN           0.623274         0.115298      0.586498        0.551789           -0.105797         0.728907   -0.042119        -0.550338   0.330242        -0.389512      0.866656    -0.042458       0.724416            -0.042236          0.325791            0.691677        -0.063891       0.439605    -0.274110   0.484703                   -0.884769        0.379161      -0.042522       0.512847       -0.042480
U.S. Dollar                     0.291582 -0.210587      0.210295            -0.042303     1.000000        0.822036           0.607010       0.999999       0.580842       -0.340426       0.645133        -0.025276      0.465683        0.019485      0.063391     -0.182763          0.401028         0.367329      0.872862           0.781126      0.926025            0.164293           0.238602    0.405865       0.902196           NaN           0.470035         0.946580      0.403862        0.641744            0.350211        -0.474763    1.000000         0.997159   0.963550         0.203239      0.124429     0.999999       0.521178             0.999999          0.645133            0.596483         0.999985      -0.671798    -0.734504   0.457371                    0.135467       -0.481887       0.999999       0.665831        0.999999
Algerian Dinar                  0.815216  0.259964     -0.388099             0.613186     0.822036        1.000000           0.908465       0.822349       0.883366        0.401592       0.851882         0.295338      0.774855        0.518779      0.406637      0.311716          0.570454         0.837613      0.923232           0.679649      0.889048            0.853723          -0.063087    0.609129       0.617849           NaN           0.892976         0.848173      0.740673        0.891683            0.246243         0.092266    0.822413         0.982313   0.726759         0.124527      0.783491     0.822200       0.885316             0.821995          0.851882            0.910574         0.872504      -0.157963    -0.561866   0.917543                   -0.321122        0.600139       0.821881       0.601316        0.822238
Australian Dollar               0.077983  0.331588     -0.582032             0.579213     0.607010        0.908465           1.000000       0.607349       0.957234        0.071958       0.641138         0.422272      0.761295        0.477744      0.532192      0.369431          0.810955         0.855761      0.921475           0.883332      0.588544            0.602386           0.005796    0.618004       0.727243           NaN           0.824098         0.745382      0.573500        0.938209            0.429160         0.155883    0.607400        -0.250614   0.529584        -0.158866      0.592071     0.607177       0.855181             0.607159          0.641138            0.913906         0.687806      -0.067537    -0.651600   0.769542                   -0.504815       -0.677335       0.607053       0.710815        0.607077
Bahrain Dinar                   0.291926 -0.209926      0.209957            -0.042220     0.999999        0.822349           0.607349       1.000000       0.581435       -0.340569       0.645139        -0.025220      0.465498        0.019696      0.064013     -0.182083          0.401776         0.367306      0.873195           0.781033      0.926067            0.164492           0.238321    0.405713       0.902448           NaN           0.470234         0.946419      0.404473        0.641833            0.351013        -0.474374    1.000000         0.997209   0.963562         0.202730      0.124805     1.000000       0.521161             0.999999          0.645139            0.596910         0.999984      -0.671219    -0.734555   0.457699                    0.135350       -0.482659       0.999999       0.666037        0.999999
Botswana Pula                   0.467693  0.469668     -0.627015             0.689069     0.580842        0.883366           0.957234       0.581435       1.000000        0.220811       0.681108         0.293106      0.677797        0.536362      0.727982      0.518708          0.937232         0.731111      0.930798           0.035487      0.544800            0.813517          -0.580269    0.575393      -0.109915           NaN           0.807082         0.735655      0.934872        0.913899            0.649925         0.377984    0.581392        -0.525282   0.586934        -0.754204      0.919410     0.581144       0.875297             0.581041          0.681108            0.977147         0.671245      -0.068228    -0.707980   0.725779                   -0.575553       -0.344260       0.580858       0.861270        0.581198
Brazilian Real                  0.320508  0.383645     -0.641122             0.731765    -0.340426        0.401592           0.071958      -0.340569       0.220811        1.000000       0.291111         0.422372      0.461093        0.753559      0.270008      0.412835         -0.029893         0.355827     -0.056475          -0.466357     -0.288645            0.614313          -0.528494    0.454859      -0.691823           NaN           0.404660        -0.134970      0.300098        0.108258           -0.439459         0.662328   -0.340516        -0.365411   0.006996        -0.104869      0.548924    -0.340877       0.328958            -0.340426          0.291111            0.249574        -0.348204       0.604634     0.172026   0.448202                   -0.449111        0.935040      -0.340725      -0.001463       -0.340619
Brunei Dollar                   0.499400  0.103766     -0.260258             0.325791     0.645133        0.851882           0.641138       0.645139       0.681108        0.291111       1.000000        -0.039829      0.606225        0.359176      0.403381      0.153361          0.445626         0.582019      0.798249           0.698221      0.898149            0.573744          -0.479244    0.459155       0.701914           NaN           0.768575         0.755778      0.568978        0.632477            0.212353        -0.050168    0.645089         0.246787   0.738859        -0.049323      0.488194     0.644860       0.640310             0.645088          1.000000            0.689421         0.643059      -0.252453    -0.539708   0.888381                   -0.023091        0.088457       0.644950       0.822605        0.644944

In [21]:


# Find the currency with the highest correlation (excluding itself)
most_correlated_currency = indian_rupee_correlation.dropna().drop('Indian Rupee').abs().idxmax()
print(most_correlated_currency)

# Print the most correlated currency
print(f"The Indian Rupee is most correlated with the {most_correlated_currency}")

Pakistani Rupee
The Indian Rupee is most correlated with the Pakistani Rupee

In [24]:
# Standardizing the currency names to match the index
selected_currencies = ['Australian Dollar', 'U.S. Dollar', 'Japanese Yen', 'Euro']

# Select the four rows in the correlation matrix for Indian Rupee
selected_correlations = indian_rupee_correlation.loc[selected_currencies]

# Display the selected correlations
selected_correlations

Australian Dollar    0.921475
U.S. Dollar          0.872862
Japanese Yen        -0.270123
Euro                 0.243851
Name: Indian Rupee, dtype: float64

In [28]:
# Define the list of currencies correctly
selected_currencies = ['Indian Rupee', 'Japanese Yen', 'U.S. Dollar', 'Euro',
                       'Australian Dollar', 'U.K. Pound Sterling', 'Chinese Yuan']

# Use .loc[] to select multiple columns
seven_currency_correlation = correlation_matrix.loc[selected_currencies, selected_currencies]

# Print the result
print(seven_currency_correlation)

                     Indian Rupee  Japanese Yen  U.S. Dollar      Euro  Australian Dollar  U.K. Pound Sterling  Chinese Yuan
Indian Rupee             1.000000     -0.270123     0.872862  0.243851           0.921475             0.314681      0.304050
Japanese Yen            -0.270123      1.000000     0.210295 -0.645719          -0.582032            -0.970308      0.117566
U.S. Dollar              0.872862      0.210295     1.000000 -0.210587           0.607010            -0.042303      0.291582
Euro                     0.243851     -0.645719    -0.210587  1.000000           0.331588             0.531150      0.151596
Australian Dollar        0.921475     -0.582032     0.607010  0.331588           1.000000             0.579213      0.077983
U.K. Pound Sterling      0.314681     -0.970308    -0.042303  0.531150           0.579213             1.000000      0.108695
Chinese Yuan             0.304050      0.117566     0.291582  0.151596           0.077983             0.108695      1.000000

In [42]:
import numpy as np

# Replace the diagonal values with NaN to ignore self-correlation
np.fill_diagonal(seven_currency_correlation.values, np.nan)

# Find the minimum correlation value (most negative)
min_correlation = seven_currency_correlation.min().min()
print(min_correlation)

# Find the currency pair corresponding to the minimum correlation
min_pair = seven_currency_correlation.stack().idxmin()
print(min_pair)

print(f"Highest negative correlation is between {min_pair[0]} and {min_pair[1]} with a value of {min_correlation}")

-0.970308318144789
('Japanese Yen', 'U.K. Pound Sterling')
Highest negative correlation is between Japanese Yen and U.K. Pound Sterling with a value of -0.970308318144789